eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
okta:
  oauth2:
    issuer: https://dev-04403317.okta.com/oauth2/default
    audience: api://default
